name: NeoLib
version: ${version}
main: me.neondeex.neolib.NeoLib
api-version: '26.2'
author: neondeex
description: Libreria central para plugins de neondeex

depend:
  - CommandAPI

soft-depend:
  - Vault
  - PlaceholderAPI
  - WorldGuard
